name: Python Calculator Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Puedes cambiar esto si usas otra versión

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        # No tienes requirements.txt, pero puedes agregarlo si algún día tienes dependencias

    - name: Ejecutar pruebas
      run: |
        python -m unittest discover -s tests
